version: '3'
services:
  db:
    container_name: mysql_db
    image: mysql:5.7
    volumes:
      - ~/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: SdXbrfuypaVy
  app:
    container_name: app
    image: sota2502/heroku-app
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile
    command: /bin/bash entrypoint.sh
    # command: /bin/bash
    tty: true
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
     - db
